/**
 * app/layout.tsx
 * The root layout component for the app.
 * @AshokSaravanan222
 * 09.01.2024
 */
import '@mantine/core/styles.css';
import '@mantine/notifications/styles.css';

import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import { Notifications } from '@mantine/notifications';
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider>
          {/* Mantine components must be wrapped by MantineProvider */}
          <Notifications />
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
