from app.services.base_processor import Summary
import os
from pylatex import Document, Section, Command, Package
from pylatex.utils import NoEscape
import re
from app.extensions import SUMMARIES_DIR

class SummaryDownloader:
    def __init__(self, summary: Summary):
        self.summary = summary

    def download_text(self):
        """Download summary as text file"""
        name = self.summary['id']
        content = self.summary['preamble'] + "\n\n" + self.summary['content'] + "\n\n" + self.summary['conclusion']
        
        # Create directory if it doesn't exist
        os.makedirs(os.path.join(SUMMARIES_DIR, name), exist_ok=True)
        
        filename = f"{name}.txt"
        filepath = os.path.join(SUMMARIES_DIR, name, filename)
        
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
            
        return filepath

    def download_pdf(self):
        """Download summary as PDF file"""
        name = self.summary['id']
        content = self.summary['preamble'] + "\n\n" + self.summary['content'] + "\n\n" + self.summary['conclusion']
        
        # Create directory if it doesn't exist
        os.makedirs(os.path.join(SUMMARIES_DIR, name), exist_ok=True)
        
        base_filename = f"{name}"
        success = self.save(name, content, base_filename, pdf=True)
        
        if success:
            return os.path.join(SUMMARIES_DIR, name, f"{base_filename}.pdf")
        return None

    def download_latex(self):
        """Download summary as LaTeX file"""
        name = self.summary['id']
        content = self.summary['preamble'] + "\n\n" + self.summary['content'] + "\n\n" + self.summary['conclusion']
        
        base_filename = f"{name}"
        success = self.save(name, content, base_filename, pdf=False)
        
        if success:
            return os.path.join(SUMMARIES_DIR, name, f"{base_filename}.tex")
        return None
    
    def save(self, name: str, summary: str, base_filename: str, pdf: bool = True):
        """
        Save processed summary to a LaTeX PDF file using PyLaTeX.
        """
        geometry_options = {
            "margin": "1in",
            "headheight": "14pt",
            "headsep": "25pt"
        }
        doc = Document(geometry_options=geometry_options)
        
        # Add packages
        for pkg in ['hyperref', 'enumitem', 'fancyhdr', 'xcolor', 'url', 'breakurl']:
            doc.packages.append(Package(pkg))

        doc.preamble.append(NoEscape(r'''
            \hypersetup{
                colorlinks=true,
                linkcolor=blue,
                filecolor=magenta,
                urlcolor=blue
            }
            \pagestyle{fancy}
            \fancyhf{}
            \rhead{Generated on \today}
            \cfoot{\thepage}
            
            % Configure enumeration settings
            \setlist[enumerate,1]{label=\arabic*.}
            \setlist[enumerate,2]{label=\alph*.}
            \setlist[enumerate,3]{label=\Alph*.}
            \setlist[enumerate]{itemsep=0.5em}
            
            % Define a command for red text
            \newcommand{\incorrect}[1]{\textcolor{red}{#1}}
        '''))
        doc.preamble.append(Command('lhead', f'{name}'))
        
        # Title
        doc.preamble.append(Command('title', f'Summary for {name}'))
        doc.preamble.append(Command('author', 'Generated by Scribe.AI'))
        doc.preamble.append(Command('date', NoEscape(r'\today')))
        doc.append(NoEscape(r'\maketitle'))

        # Questions Section
        with doc.create(Section('Summary')):
            doc.append(NoEscape(summary))

        filename = os.path.join(SUMMARIES_DIR, name, base_filename)

        if pdf:
            log_dir = "_logs"
            # Generate PDF with logs in separate directory
            try:
                # Generate PDF with logs in separate directory
                doc.generate_pdf(
                    filename,
                    clean_tex=False,
                    compiler='latexmk',
                    compiler_args=[
                        '-pdf',
                        '-interaction=nonstopmode',
                        '-file-line-error',
                        '-shell-escape',
                        '-8bit',
                        # Separate auxiliary files into logs directory
                        f'-aux-directory={log_dir}',
                        '-recorder',
                        '-verbose'
                    ]
                )
                
                # Handle log files
                log_extensions = ['.log', '.aux', '.out', '.fls']
                for ext in log_extensions:
                    src_file = os.path.join(SUMMARIES_DIR, name, log_dir, f"{base_filename}{ext}")
                    if os.path.exists(src_file):
                        # Display log content for debugging
                        if ext == '.log':
                            print(f"\nContents of log file:")
                            with open(src_file, 'r', encoding='utf-8', errors='ignore') as f:
                                lines = f.readlines()
                                print("..." if len(lines) > 50 else "")
                                for line in lines[-50:]:
                                    if "!" in line or "Error" in line or "Warning" in line:
                                        print(f"ERROR/WARNING: {line.strip()}")
                    
                print(f"PDF generated successfully: {filename}.pdf")
                # Clean up the .tex file if successful
                if os.path.exists(f"{filename}.tex"):
                    os.remove(f"{filename}.tex")
                return True

            except Exception as e:
                error_msg = str(e)
                print(f"Error during compilation: {error_msg}")
                
                # Error analysis and log display
                if "! LaTeX Error:" in error_msg:
                    latex_error = re.search(r'! LaTeX Error:(.*?)\n', error_msg)
                    if latex_error:
                        print(f"LaTeX Error: {latex_error.group(1).strip()}")
                elif "! Package" in error_msg:
                    package_error = re.search(r'! Package (.*?) Error:(.*?)\n', error_msg)
                    if package_error:
                        print(f"Package {package_error.group(1)} Error: {package_error.group(2).strip()}")
                elif "! Missing" in error_msg:
                    missing_error = re.search(r'! Missing (.*?) inserted', error_msg)
                    if missing_error:
                        print(f"Missing character error: {missing_error.group(1)}")
                
                # Check log files in the log directory
                for ext in ['.log', '.aux', '.out']:
                    log_file = os.path.join(SUMMARIES_DIR, name, log_dir, f"{base_filename}{ext}")
                    if os.path.exists(log_file):
                        print(f"\nContents of {log_file}:")
                        with open(log_file, 'r', encoding='utf-8', errors='ignore') as f:
                            for line in f:
                                if any(marker in line for marker in ["!", "Error", "Warning"]):
                                    print(line.strip())
                return False
        else:
            # remove .tex from filename
            filename = filename.replace('.tex', '')
            doc.generate_tex(filename)
            return True
